import type { Metadata } from "next";
import { Lora, Outfit } from "next/font/google";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
const lora = Lora({ subsets: ["latin"], variable: "--font-lora" });

export const metadata: Metadata = {
  title: "Abhin Rustagi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${lora.variable}`}>
      <body className="mx-auto my-20 w-full max-w-[40rem]">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
